services:
  db:
    image: postgres:14
    volumes:
      - db_pg_data:/var/lib/postgresql/data

      # Host mount for one-time initialization
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      DATABASE_NAME: rails_book_crud_app_development
    ports:
      - "5432:5432"

  #  web:
    # build: .
    #command: bundle exec rails server -b 0.0.0.0 -p 3000
    #volumes:
      #  - .:/app
    #ports:
      #  - "3000:3000"
    #depends_on:
      #  - db
    #environment:
    #  DATABASE_URL: postgres://postgres:postgres@db:5432/rails_book_crud_app_development
    #tty: true
    #stdin_open: true

volumes:
  db_pg_data:
