services:
  db:
    image: postgres:14
    volumes:
      - db_pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      DATABASE_NAME: rails_book_crud_app_development
      DATABASE_HOST: db
    ports:
      - "5432:5432"

  web:
    build: .
    command: script/docker-dev-start-web.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - opensearch
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/rails_book_crud_app_development
      OPENSEARCH_URL: http://opensearch:9200
    tty: true
    stdin_open: true

  opensearch:
    image: opensearchproject/opensearch:2.7.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"

volumes:
  db_pg_data:
